### ISSUE TITLE
Criar o site com github pages

### ISSUE THREAD

**Issue by JoseCage** [codingdojoangola/codingdojoangola.github.io#1]
@doriel @curado Sendo que ainda não temos um domínio registado para o site/landing page surgiu-me a sugestão de usarmos o [Github Pages](https://pages.github.com/#user-site), que no caso o site ficaria sobre o endereço http://codingdojoangola.github.io, bem como poderá estar sobre o domínio http://codingdojoangola.com quando for registado. Uma vez que este repositório do site é OpenSource então será só configurar o domínio e redirecionar para cá e não há necessidade de hospedagem para a landingpage..

![vazwn](https://user-images.githubusercontent.com/4200487/29037167-6b30173a-7b9a-11e7-8768-829cde731e04.jpg)

Caso concordem posso ativar aqui. Assim também todos poderão acessar e ver como está o site a cada **`push`**

**Comment by doriel** [comment]
@JoseCage por mim tudo bem...

**Comment by JoseCage** [comment]
Pronto @doriel @curado.. Tive que renomear o repo para estar sobre o domínio https://codingdojoangola.github.io..

**Comment by JoseCage** [comment]
Atendendo que o site já está online confrme citei acima com o GithubPages a isssue pode ser fechada. Caso haja necessidade podem abrir.

:woman_cartwheeling:

**Comment by JoseCage** [comment]
Finalmente. Estrutura básica criada e domínio personalizado já configurado..
*Great team*..


![cdj-works](https://user-images.githubusercontent.com/4200487/29337152-3ca23e42-8208-11e7-86cf-4ee5336e0e97.png)
